## Machine Learning Group Project -  Transit Reliability and Neighbourhood Equity in Toronto

Hi Team, since I proposed this TTC delay in Toronto Neighbourhood project, I wanted to make sure I can access all the data, and that the data links up so we can build the dataset we need.

I am developing on Google Colab, so I have to make sure certain modules are installed on the machine I'm running on.

In [176]:
# Install the Toronto Open Data wrapper
!pip install toronto-open-data

# Install Geopandas (crucial for the spatial join)
!pip install geopandas

Requirement already satisfied: toronto-open-data in /usr/local/lib/python3.12/dist-packages (0.2.1)
Requirement already satisfied: ckanapi>=0.0.0 in /usr/local/lib/python3.12/dist-packages (from toronto-open-data) (4.11)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from toronto-open-data) (2.2.2)
Requirement already satisfied: requests>=2.25.0 in /usr/local/lib/python3.12/dist-packages (from toronto-open-data) (2.32.4)
Requirement already satisfied: tqdm>=4.60.0 in /usr/local/lib/python3.12/dist-packages (from toronto-open-data) (4.67.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from ckanapi>=0.0.0->toronto-open-data) (75.2.0)
Requirement already satisfied: docopt in /usr/local/lib/python3.12/dist-packages (from ckanapi>=0.0.0->toronto-open-data) (0.6.2)
Requirement already satisfied: python-slugify>=1.0 in /usr/local/lib/python3.12/dist-packages (from ckanapi>=0.0.0->toronto-open-data) (8.0.4)
Requirement already satisfied: simplejson in /usr/local/lib/python3.12/dist-packages (from ckanapi>=0.0.0->toronto-open-data) (3.20.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->toronto-open-data) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->toronto-open-data) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->toronto-open-data) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->toronto-open-data) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.25.0->toronto-open-data) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.25.0->toronto-open-data) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.25.0->toronto-open-data) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.25.0->toronto-open-data) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->toronto-open-data) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify>=1.0->ckanapi>=0.0.0->toronto-open-data) (1.3)
Requirement already satisfied: geopandas in /usr/local/lib/python3.12/dist-packages (1.1.3)
Requirement already satisfied: numpy>=1.24 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.0.2)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas) (0.12.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from geopandas) (26.0)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.2.2)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2025.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from pyogrio>=0.7.2->geopandas) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)

This next is specific to running on Google Colab.

In [177]:
# in google colab, mount the google drive to access the data
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# TTC Bus Delay Data

I downloaded the TTC Bus Delay Data off of the following website:

https://open.toronto.ca/dataset/ttc-bus-delay-data/

I downloaded the
"TTC Bus Delay Data since 2025" in JSON Format

In [178]:
import pandas as pd
import json

# This is my subway delay data
pathToGroup = r"/content/drive/My Drive/Colab Notebooks/GroupProject"
pathToFile = r"/content/drive/My Drive/Colab Notebooks/GroupProject/TorontoDataFiles/"

fileName = 'TTC Bus Delay Data since 2025.json'

delay_dataset = pd.read_json(pathToFile+fileName)

delay_dataset.head(10)

,_id,Date,Line,Time,Day,Station,Code,Min Delay,Min Gap,Bound,Vehicle
0,1,2025-01-01,102 MARKHAM ROAD,02:15,Wednesday,WARDEN STATION,MFESA,20,40,N,3442
1,2,2025-01-01,65 PARLIAMENT,02:15,Wednesday,KIPLING STATION,MFUS,0,0,None,0
2,3,2025-01-01,64 MAIN,02:40,Wednesday,BROADVIEW STATION,MFUI,0,0,None,8546
3,4,2025-01-01,100 FLEMINGDON PARK,02:43,Wednesday,OVERLEA AND THORNCLIFF,MFSAN,17,32,N,8693
4,5,2025-01-01,34 EGLINTON EAST,03:05,Wednesday,EGLINTON AND DON MILLS,MFUI,20,40,W,8801
5,6,2025-01-01,320 YONGE,03:15,Wednesday,YONGE AND ELM,MFUS,0,0,None,0
6,7,2025-01-01,307 BATHURST,03:20,Wednesday,BATHURST AND DUNDAS,MFUS,0,0,N,0
7,8,2025-01-01,320 YONGE,03:23,Wednesday,YONGE AND SHUTER,MFSAN,5,10,N,3468
8,9,2025-01-01,112 WEST MALL,03:39,Wednesday,RENFORTH STATION,SFO,0,0,None,3306
9,10,2025-01-01,39 FINCH EAST,04:38,Wednesday,FINCH AND MCCOWAN,EFO,16,32,W,3144

In [179]:
delay_dataset.shape

(69037, 11)

So I picked the 4th row, that has a delay at OVERLEA AND THORNCLIFF	for 100 Flemingdon Park. I want to see if I can get to the Neighborhood it is from.

# TTC Routes and Schedules Data

I downloaded the data at:
https://open.toronto.ca/dataset/ttc-routes-and-schedules/

In [180]:
import pandas as pd
import requests
import io
from zipfile import ZipFile

# Example 1: Loading a local ZIP containing a CSV
# df = pd.read_csv('your_file.zip')

# Example 2: Loading from a URL (like the TTC Routes and Schedules data metadata found earlier)
zip_url = 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/7795b45e-e65a-4465-81fc-c36b9dfff169/resource/cfb6b2b8-6191-41e3-bda1-b175c51148cb/download/opendata_ttc_schedules.zip'

# Note: This specific TTC zip contains multiple text files (GTFS format).
# To load a specific file from inside the zip:
r = requests.get(zip_url)
with ZipFile(io.BytesIO(r.content)) as z:
    # List files in the zip
    print("Files in ZIP:", z.namelist())
    # Load 'routes.txt' which is a CSV-like format
    with z.open('routes.txt') as f:
        df_routes = pd.read_csv(f)
    with z.open('stops.txt') as f:
        df_route_stops = pd.read_csv(f)
    with z.open('stop_times.txt') as f:
        df_stop_times = pd.read_csv(f)
    with z.open('trips.txt') as f:
        df_trips = pd.read_csv(f)

display(df_routes.head())

Files in ZIP: ['agency.txt', 'calendar.txt', 'calendar_dates.txt', 'routes.txt', 'shapes.txt', 'stops.txt', 'stop_times.txt', 'trips.txt']

,route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color
0,1,1,1,Line 1 (Yonge-University),NaN,1,NaN,D5C82B,000000
1,10,1,10,Van Horne,NaN,3,NaN,ED1C24,FFFFFF
2,100,1,100,Flemingdon Park,NaN,3,NaN,ED1C24,FFFFFF
3,101,1,101,Downsview Park,NaN,3,NaN,ED1C24,FFFFFF
4,102,1,102,Markham Rd,NaN,3,NaN,ED1C24,FFFFFF

So now I have the TTC routes and schedules, i can see if I can map the delay at OVERLEA and THORNCLIFFE to any route stops.

In [181]:
#df_route_stops.head()

In [182]:
# find an entry in df_route_stops with stop_name column
# having 'Overlea' and 'Thorncliff'
df_route_stops[df_route_stops['stop_name'].str.contains('Overlea') &
               df_route_stops['stop_name'].str.contains('Thorncliff')]

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station,stop_timezone,wheelchair_boarding
215,8011,8011,Overlea Blvd at Thorncliffe Park Dr (East),NaN,43.707250,-79.344028,NaN,NaN,NaN,NaN,NaN,1
486,8012,8012,Overlea Blvd at Thorncliffe Park Dr (West),NaN,43.705197,-79.349856,NaN,NaN,NaN,NaN,NaN,1
3663,4520,4520,Overlea Blvd at Thorncliffe Park Dr (West),NaN,43.704776,-79.349853,NaN,NaN,NaN,NaN,NaN,1
4108,8361,8361,Thorncliffe Park Dr East at Overlea Blvd South...,NaN,43.707006,-79.343507,NaN,NaN,NaN,NaN,NaN,1
6296,4518,4518,Overlea Blvd at Thorncliffe Park Dr (East) Wes...,NaN,43.707457,-79.344198,NaN,NaN,NaN,NaN,NaN,1
6990,8352,8352,Thorncliffe Park Dr (East) at Overlea Blvd,NaN,43.706926,-79.343188,NaN,NaN,NaN,NaN,NaN,1

In [183]:
df_route_stops[df_route_stops['stop_name'].str.contains('Warden Sta') ]

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station,stop_timezone,wheelchair_boarding
8150,13732,13732,Warden Station - Eastbound Platform,NaN,43.712149,-79.278785,NaN,NaN,NaN,NaN,NaN,1
8153,13731,13731,Warden Station - Westbound Platform,NaN,43.710949,-79.279085,NaN,NaN,NaN,NaN,NaN,1
9124,16636,16636,Warden Station,NaN,43.709817,-79.280007,NaN,NaN,NaN,NaN,NaN,1
9125,16639,16639,Warden Station,NaN,43.710364,-79.279471,NaN,NaN,NaN,NaN,NaN,1
9126,16640,16640,Warden Station,NaN,43.710463,-79.280181,NaN,NaN,NaN,NaN,NaN,1
9127,16642,16642,Warden Station,NaN,43.710938,-79.280430,NaN,NaN,NaN,NaN,NaN,1
9128,16643,16643,Warden Station,NaN,43.711198,-79.280529,NaN,NaN,NaN,NaN,NaN,1
9138,16638,16638,Warden Station,NaN,43.710158,-79.279509,NaN,NaN,NaN,NaN,NaN,1

The `delay_with_neighborhood` DataFrame now contains the original bus delay data along with `latitude`, `longitude`, `AREA_NAME`, and `AREA_SHORT_CODE` for each delay entry that could be successfully mapped to a geographic location and then to a Toronto neighborhood.

Note that some entries might have `NaN` for `AREA_NAME` and `AREA_SHORT_CODE` if their coordinates didn't fall within any of the defined neighborhood boundaries, or if no coordinates could be found for the original station name.

So as you can see, we found multiple bus stops at Overlead and Thorncliffe. So we can probably do more data cleaning to get the exact stop it was at, or we can take the mean longitude and latitude and use that to map it to a neighborhood.

# Toronto Neighborhoods

https://open.toronto.ca/dataset/neighbourhoods/

I downloaded this 158-neighbourhoods proile

https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/fc443770-ef0a-4025-9c2c-2cb558bfab00/resource/0719053b-28b7-48ea-b863-068823a93aaa/download/Neighbourhoods%20-%204326.geojson

I just used the longitude and latitude of stop_id 8011 (the first entry above) to see if it works.

In [184]:
import geopandas as gpd
from shapely.geometry import Point

# 1. Load the Toronto 158-Neighborhood boundaries
gdf_neighborhoods = gpd.read_file(pathToFile + "Neighbourhoods - 4326.geojson")

# 2. Define your point (Longitude first for Shapely!)
lon, lat = -79.344028, 43.707250
my_point = Point(lon, lat)

# 3. Create a GeoDataFrame for your point(s)
gdf_point = gpd.GeoDataFrame([{'geometry': my_point}], crs="EPSG:4326")

# 4. Perform the Spatial Join
result = gpd.sjoin(gdf_point, gdf_neighborhoods, how="left", predicate="within")

# 5. Extract the Neighborhood Name and Number
neighborhood_name = result['AREA_NAME'].iloc[0]
# Usually 'AREA_SHORT_CODE' contains the ID/Number (e.g., 43)
neighborhood_number = result['AREA_SHORT_CODE'].iloc[0]

print(f"The coordinate maps to: {neighborhood_name} (Neighborhood #{neighborhood_number})")

# Display first few columns of the result to see all available attributes
display(result.head())

The coordinate maps to: Thorncliffe Park (Neighborhood #055)

,geometry,index_right,_id,AREA_ID,AREA_ATTR_ID,PARENT_AREA_ID,AREA_SHORT_CODE,AREA_LONG_CODE,AREA_NAME,AREA_DESC,CLASSIFICATION,CLASSIFICATION_CODE,OBJECTID
0,POINT (-79.34403 43.70725),129,130,2502237,26022752,None,055,055,Thorncliffe Park,Thorncliffe Park (55),Neighbourhood Improvement Area,NIA,17826801.0

# Toronto Neighborhood Profile Data

Now I will load the Neighbourhood profile data, from the census 2021.

You must get the 158 neighbourhood model after 2021, else it is not current and won't match our transit data from 2025.

https://open.toronto.ca/dataset/neighbourhood-profiles/

In [185]:
df_hoods = pd.read_excel(pathToFile+"neighbourhood-profiles-2021-158-model.xlsx", skiprows= 0, header = 0, index_col = 0, sheet_name="hd2021_census_profile")

df_hoods.head(20)

,West Humber-Clairville,Mount Olive-Silverstone-Jamestown,Thistletown-Beaumond Heights,Rexdale-Kipling,Elms-Old Rexdale,Kingsview Village-The Westway,Willowridge-Martingrove-Richview,Humber Heights-Westmount,Edenbridge-Humber Valley,Princess-Rosethorn,Eringate-Centennial-West Deane,Markland Wood,Etobicoke West Mall,Kingsway South,Stonegate-Queensway,New Toronto,Long Branch,Alderwood,Humber Summit,Humbermede,Pelmo Park-Humberlea,Black Creek,Glenfield-Jane Heights,York University Heights,Rustic,Maple Leaf,Brookhaven-Amesbury,Yorkdale-Glen Park,Englemount-Lawrence,Clanton Park,Bathurst Manor,Westminster-Branson,Newtonbrook West,Willowdale West,Lansing-Westgate,Bedford Park-Nortown,St.Andrew-Windfields,Bridle Path-Sunnybrook-York Mills,Banbury-Don Mills,Victoria Village,Flemingdon Park,Pleasant View,Don Valley Village,Hillcrest Village,Bayview Woods-Steeles,Newtonbrook East,Bayview Village,Henry Farm,O`Connor Parkview,Thorncliffe Park,Leaside-Bennington,Broadview North,Old East York,Danforth-East York,Woodbine-Lumsden,Taylor Massey,East End Danforth,The Beaches,Woodbine Corridor,Greenwood-Coxwell,Danforth,Playter Estates-Danforth,North Riverdale,Blake-Jones,South Riverdale,Cabbagetown-South St. James Town,Regent Park,Moss Park,North St. James Town,Kensington-Chinatown,University,Palmerston-Little Italy,Trinity-Bellwoods,Dufferin Grove,Little Portugal,South Parkdale,Roncesvalles,High Park-Swansea,High Park North,Runnymede-Bloor West Village,Junction Area,Weston-Pelham Park,Corso Italia-Davenport,Wychwood,Annex,Casa Loma,Yonge-St. Clair,Rosedale-Moore Park,Mount Pleasant East,Yonge-Eglinton,Forest Hill South,Forest Hill North,Lawrence Park South,Lawrence Park North,Humewood-Cedarvale,Oakwood Village,Briar Hill-Belgravia,Caledonia-Fairbank,Keelesdale-Eglinton West,Rockcliffe-Smythe,Beechborough-Greenbrook,Weston,Lambton Baby Point,Mount Dennis,Steeles,Tam O'Shanter-Sullivan,Wexford/Maryvale,Clairlea-Birchmount,Oakridge,Birchcliffe-Cliffside,Cliffcrest,Kennedy Park,Ionview,Dorset Park,Agincourt South-Malvern West,Agincourt North,Milliken,Centennial Scarborough,Highland Creek,Morningside,West Hill,Eglinton East,Scarborough Village,Guildwood,Golfdale-Cedarbrae-Woburn,Woburn North,West Rouge,Morningside Heights,Malvern West,Malvern East,L'Amoreaux West,East L'Amoreaux,Parkwoods-O'Connor Hills,Fenside-Parkwoods,Yonge-Doris,East Willowdale,Avondale,Oakdale-Beverley Heights,Downsview,Bendale-Glen Andrew,Bendale South,Islington,Etobicoke City Centre,Mimico-Queensway,Humber Bay Shores,West Queen West,Fort York-Liberty Village,Wellington Place,Harbourfront-CityPlace,St Lawrence-East Bayfront-The Islands,Church-Wellesley,Downtown Yonge East,Bay-Cloverhill,Yonge-Bay Corridor,Junction-Wallace Emerson,Dovercourt Village,North Toronto,South Eglinton-Davisville
Neighbourhood Name,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Neighbourhood Number,1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,18,19,20,21,22,23,24,25,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,46,47,48,49,50,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,78,79,80,81,83,84,85,86,87,88,89,90,91,92,94,95,96,97,98,99,100,101,102,103,105,106,107,108,109,110,111,112,113,114,115,116,118,119,120,121,122,123,124,125,126,128,129,130,133,134,135,136,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174
TSNS 2020 Designation,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Emerging Neighbourhood,Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area (formerly Woburn),Neighbourhood Improvement Area (formerly Woburn),Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Emerging Neighbourhood,Emerging Neighbourhood,Emerging Neighbourhood,Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area (formerly Downs...,Neighbourhood Improvement Area (formerly Downs...,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood
Total - Age groups of the population - 25% sample data,33300,31345,9850,10375,9355,22005,22445,10005,15190,11170,18450,10365,11865,8855,25650,11345,11360,12595,12185,16955,11290,21145,30020,28255,9390,9845,17495,16625,21285,17620,15955,25705,23805,17160,15910,22145,16960,8940,27155,17365,22530,15220,26775,16345,12085,15345,22330,19840,18405,20400,16535,10955,9160,17065,7915,15025,21840,21510,12205,14120,9305,7680,11290,7475,27815,11020,12750,21490,18535,18120,6435,13120,15415,11215,15485,20495,14610,22665,21855,10120,14010,10680,13200,12800,29300,11350,12905,20080,16370,12410,10860,12290,14960,14675,13845,20710,14575,10015,11390,22235,6260,18675,7965,13055,22765,27205,28345,26840,13705,22700,16130,17110,13365,24305,24170,27540,23980,13380,12625,17660,28140,22535,16520,9680,27085,26580,20670,24940,17320,26095,21545,21495,13965,20510,20160,15485,13790,21420,17970,18685,10725,23460,23600,17045,22605,13170,19915,25570,28135,31285,22320,17700,16670,12645,23180,12380,15885,22735
0 to 14 years,4295,5690,1495,1575,1610,3915,3500,1370,2070,1750,2640,1315,1780,1435,4225,1645,1595,2035,1840,3025,1690,4005,4950,3860,1625,1455,3065,2060,4310,2845,2275,3385,2605,1770,2325,3985,2430,1315,3470,2710,4155,1810,3825,1940,1315,1570,2390,2870,2905,4975,2905,1465,1420,3070,1290,2680,3735,3660,2315,2550,1535,1090,1790,1260,3930,900,1745,1570,2165,1245,505,1195,1600,1210,1500,1920,2130,3385,2780,2005,2050,1565,1850,1770,2435,1175,1310,2395,2780,1720,1360,1890,2450,2965,2135,3075,1910,1440,1620,3325,1030,3120,1540,2145,2755,3665,4175,4495,2565,3440,2510,2585,2215,3780,3005,3400,3225,2145,1485,2920,4470,3780,3110,1325,4940,4010,3010,4080,2830,3915,2725,2915,2285,3020,2170,2205,1545,3795,2555,2610,1610,3430,2785,2395,1700,1125,1205,1130,2065,2285,895,1055,745,970,3075,1365,1315,2190
0 to 4 years,1460,1650,505,505,440,1245,1065,395,520,545,800,345,630,290,1345,590,610,720,525,990,565,1165,1455,1260,470,450,990,735,1395,945,735,1255,940,540,710,1065,540,275,990,880,1390,420,1210,455,360,515,855,1070,935,1585,665,495,400,1015,480,990,1170,1090,750,915,500,320,480,365,1460,380,600,645,725,490,165,365,500,385,570,705,680,965,955,600,705,585,660,590,880,345,470,635,845,495,335,590,550,755,655,1100,715,515,570,1115,290,1120,435,710,735,1255,1260,1440,790,1100,720,745,735,1215,945,965,970,615,415,835,1330,1110,885,465,1470,1295,830,1225,820,1095,780,780,605,940,735,665,630,1215,935,860,420,960,1245,970,795,495,645,710,1030,1045,495,480,370,500,1135,445,535,910
5 to 9 years,1345,1860,540,615,480,1325,1190,430,740,590,835,385,620,545,1455,550,545,715,600,945,535,1365,1635,1325,560,535,930,575,1395,955,850,1075,785,520,740,1340,760,455,1090,905,1375,595,1280,640,435,540,815,1010,1020,1770,1020,505,470,1155,450,860,1340,1245,800,935,535,395,655,465,1315,280,530,540,805,360,185,405,555,450,480,660,645,1155,935,705,680,540,695,545,780,395,410,825,950,595,455,610,805,1015,705,1035,650,455,490,1040,325,1085,520,740,945,1115,1465,1635,910,1160,820,870,750,1265,955,1230,1265,720,495,955,1530,1345,1065,460,1765,1340,1065,1325,980,1330,945,1075,830,930,785,785,540,1300,805,930,520,1270,880,760,475,370,320,305,655,690,230,325,255,270,1020,430,390,670
10 to 14 years,1485,2175,455,455,685,1350,1240,540,815,610,1005,585,530,595,1425,510,440,600,710,1090,590,1470,1865,1275,600,470,1145,750,1525,945,690,1050,875,710,870,1580,1135,585,1390,925,1390,790,1340,845,520,515,725,795,950,1615,1225,470,550,905,360,830,1225,1325,765,700,505,375,655,425,1160,235,605,390,645,405,160,430,545,375,445,550,800,1270,885,700,660,455,495,635,775,435,435,930,985,630,580,695,1090,1195,775,945,545,465,555,1170,415,920,590,700,1075,1285,1445,1420,865,1185,965,965,730,1305,1100,1210,985,805,575,1130,1615,1325,1165,400,1700,1370,1120,1535,1030,1490,1000,1055,855,1150,655,755,375,1275,815,825,675,1210,660,665,430,260,235,120,385,550,175,245,120,200,925,490,390,610
15 to 64 years,23640,21490,6615,6950,6355,14385,13865,6245,9650,7110,11820,6290,8165,5355,16795,7880,8115,8280,7935,11520,7830,14125,19925,20675,6050,6550,12000,11600,13380,12230,10855,17015,16895,11960,11155,13770,10955,5435,16760,11300,15135,10060,17995,9700,7350,10655,15955,15110,12410,13125,10870,7615,6070,11155,5345,10600,15120,14165,8390,9695,6115,5100,7565,5170,20515,8005,9755,17755,14470,14070,4875,9850,11450,8385,12190,16180,10590,15555,15730,6710,10190,7625,9260,8685,21075,7260,8305,12095,10805,8740,6820,8090,9900,9530,9540,13975,10285,7070,7840,14815,4300,12875,5205,9155,13790,17365,19410,18675,9440,15235,10670,11615,9060,16715,16685,17705,15210,8505,8270,11855,19125,15195,11145,5780,17950,18440,13365,17160,11965,17645,13485,14210,9260,14305,14700,10525,10870,14470,12695,12665,7355,15290,17800,11955,17340,10930,17915,23630,24540,25015,19315,14695,13815,10820,17200,9040,12780,17495
15 to 19 years,1860,2280,570,515,635,1245,1175,525,885,755,1000,570,645,580,1225,435,440,475,760,1060,630,1470,2080,1545,590,475,1105,910,1530,950,860,1215,1210,715,830,1560,1150,650,1330,895,1380,795,1315,780,635,655,785,785,1070,1275,1285,350,495,770,290,725,1060,1220,580,505,370,335,625,360,885,300,640,530,690,605,235,365,455,410,410,710,650,1085,765,620,575,510,550,530,865,480,350,980,920,645,640,725,1220,1035,640,970,630,470,610,1145,355,955,540,765,1015,1290,1525,1565,870,1200,995,995,730,1375,1045,1260,995,820,700,1040,1730,1500,1085,490,1735,1380,1180,1615,1110,1520,1060,1220,965,1210,715,860,395,1230,975,995,655,1270,700,575,420,180,240,205,365,600,465,390,535,340,750,460,465,575
20 to 24 years,3175,2675,745,715,685,1605,1330,580,780,690,1160,535,640,495,1260,745,545,635,925,1295,730,1615,2275,3155,700,640,1270,1265,1380,1185,1060,1675,1760,1215,1085,1420,1130,530,1270,1135,1530,1090,1805,945,755,1075,1440,1575,1110,1245,925,570,440,665,320,940,1040,985,450,560,430,385,485,460,1195,550,1075,1830,1225,2135,605,980,900,570,825,1135,540,975,930,370,630,610,710,595,2145,580,460,1050,840,600,660,680,995,780,705,1100,855,625,655,1280,450,1175,425,870,1280,1835,1965,1785,910,1225,1110,1115,820,1675,1790,1915,1455,855,1140,1405,2135,1620,1155,495,2200,2095,1330,2025,1460,2040,1390,1450,910,1335,1305,1165,910,1525,1095,1610,900,1340,1230,750,950,540,1085,2800,2250,1990,3010,2340,3810,1825,1185,640,960,1115
25 to 29 years,3585,2550,880,785,730,1600,1370,530,830,520,980,525,935,295,1320,905,920,665,970,1255,775,1570,2015,2925,635,755,1160,1490,1275,1360,1135,1775,1995,1765,1280,960,990,425,1475,1030,2070,1140,2175,1035,805,1430,2325,2975,1180,1350,665,710,445,755,410,1230,1255,830,600,835,550,470,560,505,2365,920,1370,3210,2115,2945,925,1800,1810,1040,2275,2440,1165,1435,1845,395,1065,795,1060,975,3535,925,1075,1045,860,1055,740,725,745,540,1135,1395,1105,720,845,1500,440,1385,340,975,1325,2015,2245,1790,935,1260,1095,1245,960,1970,2345,1925,1560,730,1055,1510,2200,1575,1200,460,2305,2570,1370,2030,1565,2125,1395,1665,775,1740,2180,1175,1850,1395,1535,1690,965,1535,2755,1265,2890,1895,4525,7440,6515,5425,4080,3330,3330,2750,2190,1270,2325,3080
30 to 34 years,2500,2170,670,695,610,1495,1380,545,800,425,965,440,1065,290,1530,945,1150,865,770,1240,835,1245,1785,2330,535,535,1240,1545,1185,1370,960,1675,1875,1760,1355,915,920,360,1595,1205,1795,955,1895,870,680,1380,2545,2920,1195,1745,705,930,515,1160,680,1355,1610,1285,905,1365,725,535,750,545,3155,1045,1505,3325,2455,2200,770,1720,1945,1520,2530,2830,1495,2165,2600,590,1490,950,1305,1205,3480,1040,1380,1175,1025,1340,720,755,795,710,1310,1790,1285,855,915,1620,420,1620,450,1040,1370,1775,1970,2030,1040,1370,795,1110,1070,1695,2050,1940,1740,675,720,1175,1835,1525,1030,450,1935,2260,1135,1770,1110,1935,1295,1360,770,1665,2525,1190,2110,1355,1555,1580,735,1610,3345,1665,3690,2490,4935,5870,6305,5340,3565,2675,2085,2230,2990,1455,2740,3705
35 to 39 years,2170,1955,620,650,585,1480,1295,625,920,580,1150,535,930,410,1825,920,1085,990,730,1200,825,1370,1895,1945,555,565,1260,1120,1420,1450,1080,1745,1700,1310,1215,1175,800,250,1665,1125,1580,1005,1905,880,625,1085,2020,1975,1235,1715,840,975,630,1505,750,1355,1935,1525,1130,1450,785,625,830,580,2930,925,1180,2330,1860,1460,585,1245,1545,1270,1865,2215,1470,1930,2305,805,1345,1040,1155,1090,2445,755,1110,1230,1255,1110,620,880,770,830,1185,1730,1150,795,890,1670,480,1465,575,960,1235,1815,1830,2015,1075,1475,935,1045,1130,1575,1625,1580,1425,785,625,1065,1680,1560,1205,515,1630,1885,1310,1610,1050,1545,1095,1260,735,1480,1865,960,1645,1505,1285,1400,580,1530,2685,1630,2555,1745,2900,2920,3465,3375,2255,1645,1105,1255,2685,1115,1855,2575
40 to 44 years,1860,1950,540,655,555,1380,1390,565,975,650,985,535,775,585,1965,800,855,970,740,1220,835,1305,1765,1780,560,690,1160,910,1520,1320,1220,1720,1625,1045,1165,1415,1010,525,1605,1230,1510,810,1940,735,640,895,1555,1300,1385,1240,1065,900,755,1585,630,1250,1810,1725,1095,1195,735,625,895,665,2485,835,890,1535,1450,1010,425,835,1035,955,1310,1770,1245,1710,1705,885,1200,825,1080,965,1730,595,785,1035,1265,920,570,875,910,1105,1035,1490,1085,750,810,1545,435,1220,540,905,1245,1460,1730,1855,940,1605,965,1160,960,1535,1275,1295,1290,765,595,1240,1615,1400,1100,575,1565,1595,1245,1405,1125,1540,1170,1235,930,1365,1440,900,1135,1625,1350,965,640,1470,1890,1320,1570,1255,1605,1570,1890,1970,1275,1010,625,630,1920,885,1205,1680
45 to 49 years,1980,2075,570,655,535,1315,1310,590,950,725,1165,620,675,635,1940,795,715,895,650,980,670,1345,1790,1655,545,740,1095,1085,1345,1235,1035,1850,1620,1025,1160,1420,1045,535,1690,1105,1390,945,1835,1035,590,950,1380,965,1080,1455,1300,860,670,1315,625,1005,1680,1655,1050,1100,715,505,855,535,2210,745,785,1355,1165,880,315,780,1065,780,980,1385,1125,1670,1570,875,1110,740,855,830,1635,645,755,1200,1220,865,690,865,1120,1265,1005,1390,965,700,725,1355,400,1195,640,805,1360,1465,1850,1905,940,1690,1000,1060,705,1570,1420,1460,1375,890,645,920,1810,1465,995,640,1620,1585,1290,1385,1035,1735,1270,1280,1020,1385,1250,960,870,1425,1145,1025,665,1410,1445,1215,1335,955,930,995,1210,1625,1080,825,505,470,1605,805,935,1370
50 to 54 years,2035,2140,690,745,665,1330,1510,710,1130,825,1390,780,815,695,1890,795,735,920,795,1215,880,1420,2255,1670,560,720,1220,1205,1270,1150,1270,1710,1730,1040,1115,1600,1360,695,2140,1220,1385,1170,1785,1205,880,1020,1315,915,1410,1165,1505,845,720,1225,505,945,1705,1730,985,930,630,545,830,535,1915,825,820,1295,1265,940,340,770,965,660,765,1280,1115,1565,1350,790,990,765,870,870,1730,725,780,1315,1270,850,750,880,1200,1345,910,1405,1080,725,740,1430,475,1345,675,895,1490,1750,1950,2020,975,1715,1140,1210,850,1710,1490,2010,1590,1000,825,1190,1935,1465,1180,695,1550,1750,1340,1695,1130,1670,1605,1510,1130,1315,1275,1125,710,1565,1270,1175,730,1635,1390,1070,1210,750,655,770,975,1590,1230,855,645,450,1315,880,855,1230

In [186]:
# display hardcoded for now
df_hoods.iloc[:, 49]

Neighbourhood Name
Neighbourhood Number                                                                                                                                                                                    55
TSNS 2020 Designation                                                                                                                                                       Neighbourhood Improvement Area
Total - Age groups of the population - 25% sample data                                                                                                                                               20400
  0 to 14 years                                                                                                                                                                                       4975
    0 to 4 years                                                                                                                                                                                      1585
                                                                                                                                                                                         ...
Total - Eligibility and instruction in the minority official language, for the population in private households born between 2003 and 2015 (inclusive) - 25% sample data                              4120
  Children eligible for instruction in the minority official language                                                                                                                                  190
    Eligible children who have been instructed in the minority official language at the primary or secondary level in Canada                                                                           120
    Eligible children who have not been instructed in the minority official language at the primary or secondary level in Canada                                                                        65
  Children not eligible for instruction in the minority official language                                                                                                                             3930
Name: Thorncliffe Park, Length: 2603, dtype: object

There is too much data in the Census 2021 Data, so we will just select some rows we might be interested in, then transpose it before merging this data with the one with geometric data.

In [187]:
# too much extraneous data in the neighbourhood profile
# we won't use everything, so just keep the rows that we're
# interested in before we transpose it and add on to our
# geojson data

#drop rows that we don't care about
rows_to_keep = [0, 1, 2] # hood headings
rows_to_keep.extend([245, 246]) # income of household
rows_to_keep.extend([298,299,300]) # owner/renter
rows_to_keep.extend([1479, 1480, 1483]) # cdn citizen vs not
rows_to_keep.extend([1484, 1485, 1486]) # immigrants vs not
rows_to_keep.extend(list(range(2564,2595))) # commuting characteristics

df_hoods_subset = df_hoods.iloc[rows_to_keep]
df_hoods_subset.head(100)

,West Humber-Clairville,Mount Olive-Silverstone-Jamestown,Thistletown-Beaumond Heights,Rexdale-Kipling,Elms-Old Rexdale,Kingsview Village-The Westway,Willowridge-Martingrove-Richview,Humber Heights-Westmount,Edenbridge-Humber Valley,Princess-Rosethorn,Eringate-Centennial-West Deane,Markland Wood,Etobicoke West Mall,Kingsway South,Stonegate-Queensway,New Toronto,Long Branch,Alderwood,Humber Summit,Humbermede,Pelmo Park-Humberlea,Black Creek,Glenfield-Jane Heights,York University Heights,Rustic,Maple Leaf,Brookhaven-Amesbury,Yorkdale-Glen Park,Englemount-Lawrence,Clanton Park,Bathurst Manor,Westminster-Branson,Newtonbrook West,Willowdale West,Lansing-Westgate,Bedford Park-Nortown,St.Andrew-Windfields,Bridle Path-Sunnybrook-York Mills,Banbury-Don Mills,Victoria Village,Flemingdon Park,Pleasant View,Don Valley Village,Hillcrest Village,Bayview Woods-Steeles,Newtonbrook East,Bayview Village,Henry Farm,O`Connor Parkview,Thorncliffe Park,Leaside-Bennington,Broadview North,Old East York,Danforth-East York,Woodbine-Lumsden,Taylor Massey,East End Danforth,The Beaches,Woodbine Corridor,Greenwood-Coxwell,Danforth,Playter Estates-Danforth,North Riverdale,Blake-Jones,South Riverdale,Cabbagetown-South St. James Town,Regent Park,Moss Park,North St. James Town,Kensington-Chinatown,University,Palmerston-Little Italy,Trinity-Bellwoods,Dufferin Grove,Little Portugal,South Parkdale,Roncesvalles,High Park-Swansea,High Park North,Runnymede-Bloor West Village,Junction Area,Weston-Pelham Park,Corso Italia-Davenport,Wychwood,Annex,Casa Loma,Yonge-St. Clair,Rosedale-Moore Park,Mount Pleasant East,Yonge-Eglinton,Forest Hill South,Forest Hill North,Lawrence Park South,Lawrence Park North,Humewood-Cedarvale,Oakwood Village,Briar Hill-Belgravia,Caledonia-Fairbank,Keelesdale-Eglinton West,Rockcliffe-Smythe,Beechborough-Greenbrook,Weston,Lambton Baby Point,Mount Dennis,Steeles,Tam O'Shanter-Sullivan,Wexford/Maryvale,Clairlea-Birchmount,Oakridge,Birchcliffe-Cliffside,Cliffcrest,Kennedy Park,Ionview,Dorset Park,Agincourt South-Malvern West,Agincourt North,Milliken,Centennial Scarborough,Highland Creek,Morningside,West Hill,Eglinton East,Scarborough Village,Guildwood,Golfdale-Cedarbrae-Woburn,Woburn North,West Rouge,Morningside Heights,Malvern West,Malvern East,L'Amoreaux West,East L'Amoreaux,Parkwoods-O'Connor Hills,Fenside-Parkwoods,Yonge-Doris,East Willowdale,Avondale,Oakdale-Beverley Heights,Downsview,Bendale-Glen Andrew,Bendale South,Islington,Etobicoke City Centre,Mimico-Queensway,Humber Bay Shores,West Queen West,Fort York-Liberty Village,Wellington Place,Harbourfront-CityPlace,St Lawrence-East Bayfront-The Islands,Church-Wellesley,Downtown Yonge East,Bay-Cloverhill,Yonge-Bay Corridor,Junction-Wallace Emerson,Dovercourt Village,North Toronto,South Eglinton-Davisville
Neighbourhood Name,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Neighbourhood Number,1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,18,19,20,21,22,23,24,25,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,46,47,48,49,50,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,78,79,80,81,83,84,85,86,87,88,89,90,91,92,94,95,96,97,98,99,100,101,102,103,105,106,107,108,109,110,111,112,113,114,115,116,118,119,120,121,122,123,124,125,126,128,129,130,133,134,135,136,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174
TSNS 2020 Designation,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Emerging Neighbourhood,Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area (formerly Woburn),Neighbourhood Improvement Area (formerly Woburn),Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Emerging Neighbourhood,Emerging Neighbourhood,Emerging Neighbourhood,Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area (formerly Downs...,Neighbourhood Improvement Area (formerly Downs...,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood
Total - Age groups of the population - 25% sample data,33300,31345,9850,10375,9355,22005,22445,10005,15190,11170,18450,10365,11865,8855,25650,11345,11360,12595,12185,16955,11290,21145,30020,28255,9390,9845,17495,16625,21285,17620,15955,25705,23805,17160,15910,22145,16960,8940,27155,17365,22530,15220,26775,16345,12085,15345,22330,19840,18405,20400,16535,10955,9160,17065,7915,15025,21840,21510,12205,14120,9305,7680,11290,7475,27815,11020,12750,21490,18535,18120,6435,13120,15415,11215,15485,20495,14610,22665,21855,10120,14010,10680,13200,12800,29300,11350,12905,20080,16370,12410,10860,12290,14960,14675,13845,20710,14575,10015,11390,22235,6260,18675,7965,13055,22765,27205,28345,26840,13705,22700,16130,17110,13365,24305,24170,27540,23980,13380,12625,17660,28140,22535,16520,9680,27085,26580,20670,24940,17320,26095,21545,21495,13965,20510,20160,15485,13790,21420,17970,18685,10725,23460,23600,17045,22605,13170,19915,25570,28135,31285,22320,17700,16670,12645,23180,12380,15885,22735
Median after-tax income of household in 2020 ($),83000,70500,78000,71000,74500,72000,81000,74000,86000,133000,93000,90000,74500,144000,88000,61600,71500,92000,73500,70500,88000,61200,65000,69000,59600,74000,67000,70500,70000,76500,81000,68500,71000,68000,83000,113000,99000,164000,78000,61600,64500,79500,75000,77500,81000,72000,72500,69000,69500,62400,123000,61200,84000,86000,84000,62800,78500,96000,83000,81000,84000,75000,93000,77500,85000,67000,60000,57600,54000,56400,68500,76500,79500,69500,73500,52000,77000,85000,71500,115000,83000,72000,82000,74500,72000,87000,79000,98000,92000,80000,90000,79000,129000,138000,72500,69000,72500,76000,69500,63200,56800,58800,87000,64000,73000,68500,74000,80000,56400,79000,82000,62800,67500,71500,71500,76500,74000,115000,105000,76500,69000,67500,65500,87000,71000,68500,95000,105000,80000,77500,66000,76000,86000,70500,64500,84000,72000,66000,73500,67000,81000,88000,71500,73500,71500,84000,78000,75000,75500,73500,53600,61600,52400,60400,75000,77000,61200,68500
Average after-tax income of household in 2020 ($),92300,78200,88800,79200,83600,85600,95400,101400,138200,164200,105600,115500,83900,211200,116200,76900,86400,105200,84300,79000,97300,68300,76300,77400,73800,90200,78200,81800,100600,99400,91500,80400,81800,85600,115200,182600,157800,310400,109700,73400,70600,91300,85100,88200,100300,90100,85300,77000,88000,68500,191200,77400,102700,104900,95700,69800,96700,138600,102700,95400,108200,109700,127900,95900,105500,93100,70500,75800,63600,73200,94400,103900,103800,83100,88900,64300,98000,120100,92400,136000,96700,81600,96600,101600,129000,183400,143600,208600,132800,119700,184400,126300,231000,185200,107700,85700,82700,87600,79800,75700,69000,70100,123500,72800,84200,80300,85800,90000,64900,103000,97800,73400,75400,79300,81000,85700,84700,125400,114900,86600,79400,75900,76000,100700,80600,76500,109900,110800,88800,86600,80100,84800,104400,80800,73500,108000,82900,78000,84200,74900,92400,114600,80300,90900,86600,104000,88600,93600,87000,91800,64800,76500,72300,77700,86700,92300,70900,82100
Total - Private households by tenure - 25% sample data,10700,9740,3245,3945,3195,7785,8600,4110,6285,3900,6845,4220,4730,3470,10515,5275,5290,4790,3930,5675,3915,7230,10000,10350,3520,3600,6395,6840,8160,7155,6065,10030,9090,7835,6555,8340,6345,3300,12215,7275,8195,5445,10235,6385,4755,6165,10455,8510,7460,7065,6435,5275,3725,6950,3380,6010,9500,9430,5235,6035,3910,3645,4905,3100,12710,6200,6110,13290,9530,9520,3240,6180,6840,5270,7890,11285,6785,10450,11100,3840,6035,4195,5215,5770,16325,5810,7210,9875,7170,6000,5075,5250,5785,5460,6335,8635,5940,3710,4385,9035,2570,7920,3105,5055,7865,10350,10260,9400,5315,9615,5875,6585,4965,8720,8890,9090,7585,4420,3795,5875,10175,8190,5955,3935,8830,9825,7025,6535,5115,8565,8295,7205,5055,8150,9845,5610,6995,7655,6975,7415,3355,9285,11925,7875,13330,7700,12415,17070,16550,18790,14670,11050,10585,7465,10185,5310,9430,13185
Owner,6995,4485,2025,1990,1760,4120,4670,2490,3550,3310,5740,3100,2645,2825,6605,2315,2665,3675,2825,2605,3185,2360,5180,4815,1330,1965,2620,3670,3530,3895,3280,4000,4550,4670,3710,5675,4050,2920,7295,3000,3560,3960,5185,4625,2650,3825,6225,3340,3410,990,4660,1630,2450,4805,2240,2020,5190,5975,3135,3560,2480,1745,2855,1680,7270,2790,1800,4660,1060,3005,1255,2565,3800,2185,3375,1710,3155,6245,3710,2990,3500,2490,3300,2920,6675,2545,2850,5690,3950,2230,2470,1835,3960,4105,2325,4355,2850,2335,2595,5075,860,2810,1830,2400,6520,5815,6050,6000,1630,6310,3730,3440,1910,5260,6190,7135,6670,4075,3275,3495,6035,3805,2675,3075,4400,5295,5585,5515,3770,6010,4505,5400,2385,2735,5470,3915,4025,3310,3675,4490,2245,6355,5960,4180,7215,4190,5780,6555,6625,7470,3565,3990,3210,2405,5105,2900,1750,4010
Renter,3705,5260,1220,1955,1430,3660,3930,1625,2735,590,1105,1125,2080,650,3910,2965,2630,1110,1100,3070,730,4870,4820,5535,2195,1635,3775,3165,4630,3255,2780,6040,4540,3170,2845,2660,2295,380,4915,4280,4635,1480,5050,1755,2105,2340,4230,5175,4045,6070,1780,3645,1275,2145,1135,3985,4310,3455,2100,2470,1435,1900,2045,1425,5440,3405,4310,8630,8470,6515,1980,3620,3040,3085,4515,9580,3625,4210,7390,845,2535,1705,1915,2855,9655,3260,4355,4190,3220,3765,2610,3410,1825,1355,4010,4280,3090,1375,1785,3960,1715,5110,1275,2655,1340,4535,4220,3405,3680,3305,2150,3150,3060,3460,2700,1950,910,350,520,2380,4145,4385,3275,860,4430,4530,1440,1010,1345,2560,3790,1805,2665,5415,4370,1695,2975,4345,3300,2925,1115,2930,5965,3695,6115,3505,6630,10510,9930,11325,11110,7065,7380,5055,5080,2410,7680,9170
Total - Citizenship for the population in private households - 25% sample data,33300,31345,9850,10375,9355,22010,22445,10005,15190,11170,18450,10365,11865,8855,25655,11345,11360,12595,12185,16955,11290,21145,30025,28255,9390,9840,17495,16625,21290,17620,15955,25705,23805,17165,15910,22145,16955,8940,27150,17365,22530,15220,26770,16345,12085,15345,22330,19840,18405,20400,16535,10955,9160,17065,7915,15025,21845,21505,12205,14120,9310,7680,11290,7475,27815,11020,12750,21495,18535,18120,6435,13120,15415,11210,15485,20500,14615,22665,21855,10120,14010,10680,13200,12800,29300,11350,12905,20080,16370,12405,10860,12295,14960,14675,13845,20710,14575,10015,11385,22240,6260,18680,7965,13055,22760,27205,28340,26840,13705,22700,16130,17105,13365,24305,24170,27540,23980,13385,12630,17660,28135,22535,16525,9680,27085,26585,20670,24940,17320,26100,21545,21495,13965,20510,20160,15485,13790,21415,17970,18685,10725,23460,23600,17045,22600,13170,19910,25570,28130,31285,22320,17695,16670,12645,23180,12380,15885,22735
Canadian citizens,26285,23340,8045,8855,8200,18515,19555,9125,13815,10460,17220,9675,9925,8530,23070,9835,9840,11645,10040,12945,9960,16770,24915,20225,8105,8075,14575,13305,17560,14495,13295,19195,16655,12685,12515,19960,14280,8190,23375,14485,16975,11970,20080,13195,10060,11225,16650,11340,15785,15215,15630,9475,8495,15800,7170,11285,19885,20325,11400,12960,8560,7180,10680,6935,25570,9685,10695,17545,13175,14360,5380,11810,13465,9830,13580,17110,13505,20800,19240,9640,12940,9315,11460,11700,25420,10425,11400,17965,14745,10505,9620,10285,13685,13660,12160,17475,11660,8005,9045,18690,4915,14910,7370,10670,17830,21570,23620,22645,11130,20980,14420,14435,10445,19715,18595,22145,18795,12725,10980,14485,24545,18245,13145,9040,21855,20545,18840,21880,14535,22020,17365,16615,12350,16265,13090,11900,9315,16630,14240,14425,8775,20785,18520,15140,18610,11630,16315,19210,19420,24835,15595,13120,10885,8155,19960,11045,10945,16525
Not Canadian citizens,7010,8005,1805,1520,1155,3495,2890,880,1375,710,1230,695,1940,330,2585,1510,1520,945,2150,4010,1325,4375,5110,8030,1285,1765,2920,3320,3730,3130,2655,6510,7150,4475,3395,2185,2680,750,3780,2880,5555,3250,6695,3145,2020,4115,5675,8500,2620,5185,905,1480,665,1265,745,3735,1955,1180,805,1160,745,505,610,535,2245,1340,2055,3950,5365,3760,1055,1315,1945,1385,1900,3385,1110,1855,2610,480,1075,1360,1740,1105,3875,925,1500,2115,1625,1900,1245,2005,1275,1010,1685,3230,2915,2010,2340,3545,1345,3770,595,2385,4935,5635,4720,4200,2575,1725,1710,2675,2925,4590,5570,5395,5190,655,1640,3175,3595,4290,3380,640,5230,6030,1835,3060,2785,4070,4185,4880,1615,4240,7070,3585,4475,4790,3725,4265,1945,2680,5080,1910,3985,1545,3605,6365,8710,6450,6725,4580,5790,4490,3225,1340,4945,6210
Total - Immigrant status and period of immigration for the population in private households - 25% sample data,33300,31345,9850,10375,9355,22010,22445,10005,15190,11170,18450,10365,11865,8855,25655,11345,11360,12595,12185,16955,11290,21145,30025,28255,9390,9840,17495,16625,21290,17620,15955,25705,23805,17165,15910,22145,16955,8940,27150,17365,22530,15220,26770,16345,12085,15345,22330,19840,18405,20400,16535,10955,9160,17065,7915,15025,21845,21505,12205,14120,9310,7680,11290,7475,27815,11020,12750,21495,18535,18120,6435,13120,15415,11210,15485,20500,14615,22665,21855,10120,14010,10680,13200,12800,29300,11350,12905,20080,16370,12405,10860,12295,14960,14675,13845,20710,14575,10015,11385,22240,6260,18680,7965,13055,22760,27205,28340,26840,13705,22700,16130,17105,13365,24305,24170,27540,23980,13385,12630,17660,28135,22535,16525,9680,27085,26585,20670,24940,17320,26100,21545,21495,13965,20510,20160,15485,13790,21415,17970,18685,10725,23460,23600,17045,22600,13170,19910,25570,28130,31285,22320,17695,16670,12645,23180,12380,15885,22735
Non-immigrants,11805,9620,4055,5080,4515,10150,11495,5095,9040,7615,10295,6365,5360,6830,16105,6735,7020,8105,4845,6090,5705,7720,11295,9430,4365,4445,7590,7200,10890,8940,7145,7160,6265,5775,7585,15225,7730,5490,12640,7605,7210,5040,7885,4700,4455,4185,7250,4780,10580,6420,12785,5940,6110,11280,5295,5755,15415,16845,9060,9910,6535,5490,8395,5065,19200,6775,6245,11685,6905,8655,3760,8900,9250,6865,9975,10880,10165,15825,13845,7830,9440,5775,7630,8200,18725,7840,8740,13720,11305,8020,7510,6795,11040,10745,8895,10805,5685,4455,4810,10625,2645,8840,5445,5445,5670,9335,12365,12090,5655,16085,9370,6800,5270,8650,7370,7700,6475,8305,4690,6735,13170,8280,6570,6215,11105,9285,10615,9110,6080,9320,7130,6515,7505,8150,4605,5205,4275,8505,7655,6870,4240,13145,10750,10045,10785,8700,11485,13635,12090,16100,9970,8200,6325,4590,13320,7450,6625,11005

In [188]:
df_hoods_subset_tr = df_hoods_subset.transpose()
df_hoods_subset_tr.shape

(158, 45)

So we only kept around 45 features from the Census.

In [189]:
df_hoods_subset_tr.head()

Neighbourhood Name,Neighbourhood Number,TSNS 2020 Designation,Total - Age groups of the population - 25% sample data,Median after-tax income of household in 2020 ($),Average after-tax income of household in 2020 ($),Total - Private households by tenure - 25% sample data,Owner,Renter,Total - Citizenship for the population in private households - 25% sample data,Canadian citizens,Not Canadian citizens,Total - Immigrant status and period of immigration for the population in private households - 25% sample data,Non-immigrants,Immigrants,Total - Place of work status for the employed labour force aged 15 years and over - 25% sample data,Worked at home,Worked outside Canada,No fixed workplace address,Usual place of work,Total - Commuting destination for the employed labour force aged 15 years and over with a usual place of work - 25% sample data,Commute within census subdivision (CSD) of residence,Commute to a different census subdivision (CSD) within census division (CD) of residence,Commute to a different census subdivision (CSD) and census division (CD) within province or territory of residence,Commute to a different province or territory,Total - Main mode of commuting for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data,"Car, truck or van","Car, truck or van - as a driver","Car, truck or van - as a passenger",Public transit,Walked,Bicycle,Other method,Total - Commuting duration for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data,Less than 15 minutes,15 to 29 minutes,30 to 44 minutes,45 to 59 minutes,60 minutes and over,Total - Time leaving for work for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data,Between 5 a.m. and 5:59 a.m.,Between 6 a.m. and 6:59 a.m.,Between 7 a.m. and 7:59 a.m.,Between 8 a.m. and 8:59 a.m.,Between 9 a.m. and 11:59 a.m.,Between 12 p.m. and 4:59 a.m.
West Humber-Clairville,1,Not an NIA or Emerging Neighbourhood,33300,83000,92300,10700,6995,3705,33300,26285,7010,33300,11805,18805,15780,2815,40,2630,10290,10290,6185,0,4065,40,12920,9260,8190,1075,3110,255,80,215,12920,2305,4390,3400,1125,1695,12920,980,2445,2630,2270,1665,2935
Mount Olive-Silverstone-Jamestown,2,Neighbourhood Improvement Area,31345,70500,78200,9740,4485,5260,31345,23340,8005,31345,9620,19810,11830,1655,45,1910,8215,8215,4740,0,3465,10,10125,7400,6395,1005,2235,255,10,220,10125,1655,3275,2845,1000,1345,10125,785,1830,1855,1540,1145,2965
Thistletown-Beaumond Heights,3,Neighbourhood Improvement Area,9850,78000,88800,3245,2025,1220,9850,8045,1805,9850,4055,5210,4165,775,25,845,2515,2515,1750,0,760,0,3365,2530,2255,280,660,45,20,110,3365,550,1135,855,275,550,3365,245,680,745,660,395,635
Rexdale-Kipling,4,Not an NIA or Emerging Neighbourhood,10375,71000,79200,3945,1990,1955,10375,8855,1520,10375,5080,4820,4560,870,10,810,2875,2880,1965,0,905,10,3680,2660,2360,300,830,105,10,80,3680,590,1295,915,330,560,3680,340,695,775,665,425,775
Elms-Old Rexdale,5,Neighbourhood Improvement Area,9355,74500,83600,3195,1760,1430,9355,8200,1155,9355,4515,4600,3600,630,10,625,2345,2345,1640,0,695,0,2965,2170,1920,245,615,85,0,85,2965,380,1185,780,260,360,2965,250,585,590,510,355,675

In [190]:
gdf_neighborhoods.head()

,_id,AREA_ID,AREA_ATTR_ID,PARENT_AREA_ID,AREA_SHORT_CODE,AREA_LONG_CODE,AREA_NAME,AREA_DESC,CLASSIFICATION,CLASSIFICATION_CODE,OBJECTID,geometry
0,1,2502366,26022881,None,174,174,South Eglinton-Davisville,South Eglinton-Davisville (174),Not an NIA or Emerging Neighbourhood,NA,17824737.0,"MULTIPOLYGON (((-79.38635 43.69783, -79.38623 ..."
1,2,2502365,26022880,None,173,173,North Toronto,North Toronto (173),Not an NIA or Emerging Neighbourhood,NA,17824753.0,"MULTIPOLYGON (((-79.39744 43.70693, -79.39837 ..."
2,3,2502364,26022879,None,172,172,Dovercourt Village,Dovercourt Village (172),Not an NIA or Emerging Neighbourhood,NA,17824769.0,"MULTIPOLYGON (((-79.43411 43.66015, -79.43537 ..."
3,4,2502363,26022878,None,171,171,Junction-Wallace Emerson,Junction-Wallace Emerson (171),Not an NIA or Emerging Neighbourhood,NA,17824785.0,"MULTIPOLYGON (((-79.4387 43.66766, -79.43841 4..."
4,5,2502362,26022877,None,170,170,Yonge-Bay Corridor,Yonge-Bay Corridor (170),Not an NIA or Emerging Neighbourhood,NA,17824801.0,"MULTIPOLYGON (((-79.38404 43.64497, -79.38502 ..."

In [191]:
# combine the selected info from the census in the one with
# geographic data

# first need to convert AREA_SHORT_CODE to numbers
gdf_neighborhoods_cleaned = gdf_neighborhoods.copy()
pd.to_numeric(gdf_neighborhoods_cleaned['AREA_SHORT_CODE'], errors='coerce')
gdf_neighborhoods_cleaned.dropna(subset=['AREA_SHORT_CODE'], inplace=True)
gdf_neighborhoods_cleaned['AREA_SHORT_CODE'] = gdf_neighborhoods_cleaned['AREA_SHORT_CODE'].astype(int)

# then convert hoods neighbourhood numbers to numbers as well
df_hoods_subset_tr_cleaned = df_hoods_subset_tr.copy()
pd.to_numeric(df_hoods_subset_tr_cleaned['Neighbourhood Number'], errors='coerce')
df_hoods_subset_tr_cleaned.dropna(subset=['Neighbourhood Number'], inplace=True)
df_hoods_subset_tr_cleaned['Neighbourhood Number'] = df_hoods_subset_tr_cleaned['Neighbourhood Number'].astype(int)

gdf_neighborhoods_full = gdf_neighborhoods_cleaned.merge(df_hoods_subset_tr_cleaned, left_on='AREA_SHORT_CODE', right_on='Neighbourhood Number')

In [192]:
gdf_neighborhoods_full.shape

(158, 57)

In [193]:
gdf_neighborhoods_full.head()

,_id,AREA_ID,AREA_ATTR_ID,PARENT_AREA_ID,AREA_SHORT_CODE,AREA_LONG_CODE,AREA_NAME,AREA_DESC,CLASSIFICATION,CLASSIFICATION_CODE,OBJECTID,geometry,Neighbourhood Number,TSNS 2020 Designation,Total - Age groups of the population - 25% sample data,Median after-tax income of household in 2020 ($),Average after-tax income of household in 2020 ($),Total - Private households by tenure - 25% sample data,Owner,Renter,Total - Citizenship for the population in private households - 25% sample data,Canadian citizens,Not Canadian citizens,Total - Immigrant status and period of immigration for the population in private households - 25% sample data,Non-immigrants,Immigrants,Total - Place of work status for the employed labour force aged 15 years and over - 25% sample data,Worked at home,Worked outside Canada,No fixed workplace address,Usual place of work,Total - Commuting destination for the employed labour force aged 15 years and over with a usual place of work - 25% sample data,Commute within census subdivision (CSD) of residence,Commute to a different census subdivision (CSD) within census division (CD) of residence,Commute to a different census subdivision (CSD) and census division (CD) within province or territory of residence,Commute to a different province or territory,Total - Main mode of commuting for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data,"Car, truck or van","Car, truck or van - as a driver","Car, truck or van - as a passenger",Public transit,Walked,Bicycle,Other method,Total - Commuting duration for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data,Less than 15 minutes,15 to 29 minutes,30 to 44 minutes,45 to 59 minutes,60 minutes and over,Total - Time leaving for work for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data,Between 5 a.m. and 5:59 a.m.,Between 6 a.m. and 6:59 a.m.,Between 7 a.m. and 7:59 a.m.,Between 8 a.m. and 8:59 a.m.,Between 9 a.m. and 11:59 a.m.,Between 12 p.m. and 4:59 a.m.
0,1,2502366,26022881,None,174,174,South Eglinton-Davisville,South Eglinton-Davisville (174),Not an NIA or Emerging Neighbourhood,NA,17824737.0,"MULTIPOLYGON (((-79.38635 43.69783, -79.38623 ...",174,Not an NIA or Emerging Neighbourhood,22735,68500,82100,13185,4010,9170,22735,16525,6210,22735,11005,9360,13475,7330,95,855,5195,5200,4560,0,610,30,6055,2410,2155,255,2655,665,110,215,6055,930,1905,2005,665,550,6055,175,600,1360,1800,1390,730
1,2,2502365,26022880,None,173,173,North Toronto,North Toronto (173),Not an NIA or Emerging Neighbourhood,NA,17824753.0,"MULTIPOLYGON (((-79.39744 43.70693, -79.39837 ...",173,Not an NIA or Emerging Neighbourhood,15885,61200,70900,9430,1750,7680,15885,10945,4945,15885,6625,7135,9460,4890,35,660,3880,3880,3315,0,555,10,4540,1760,1565,195,1950,545,150,145,4540,640,1220,1670,550,465,4540,140,570,1060,1255,970,550
2,3,2502364,26022879,None,172,172,Dovercourt Village,Dovercourt Village (172),Not an NIA or Emerging Neighbourhood,NA,17824769.0,"MULTIPOLYGON (((-79.43411 43.66015, -79.43537 ...",172,Not an NIA or Emerging Neighbourhood,12380,77000,92300,5310,2900,2410,12380,11045,1340,12380,7450,4445,6430,2910,20,720,2775,2775,2495,0,270,0,3495,1645,1425,215,965,390,395,105,3495,600,1115,1115,385,285,3495,185,460,690,825,775,570
3,4,2502363,26022878,None,171,171,Junction-Wallace Emerson,Junction-Wallace Emerson (171),Not an NIA or Emerging Neighbourhood,NA,17824785.0,"MULTIPOLYGON (((-79.4387 43.66766, -79.43841 4...",171,Not an NIA or Emerging Neighbourhood,23180,75000,86700,10185,5105,5080,23180,19960,3225,23180,13320,9020,12070,5135,20,1660,5260,5260,4620,0,635,0,6925,3430,2945,485,2275,610,350,270,6925,1015,2135,2225,845,715,6925,475,1195,1335,1635,1185,1105
4,5,2502362,26022877,None,170,170,Yonge-Bay Corridor,Yonge-Bay Corridor (170),Not an NIA or Emerging Neighbourhood,NA,17824801.0,"MULTIPOLYGON (((-79.38404 43.64497, -79.38502 ...",170,Not an NIA or Emerging Neighbourhood,12645,60400,77700,7465,2405,5055,12645,8155,4490,12645,4590,5630,7475,4145,80,335,2905,2905,2640,0,260,0,3240,640,550,85,685,1675,125,125,3240,1155,1055,610,200,230,3240,60,355,745,1050,695,330

# Data Generation

So now we can perform a spatial join with the TTC bus delay, and build our data.

In [194]:
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

# --- Step 1: Create a mapping of Station names to coordinates ---

# Clean df_route_stops stop_name for better matching
df_route_stops['cleaned_stop_name'] = df_route_stops['stop_name'].str.upper().str.replace(r'[^A-Z0-9\s]', '', regex=True).str.strip()

# Initialize dictionary to store mappings from delay_dataset station names to (lat, lon)
station_to_coords = {}

# Get unique station names from delay_dataset to process them efficiently
unique_delay_stations = delay_dataset['Station'].unique()

# Iterate through each unique delay station name to find its coordinates
for delay_station in unique_delay_stations:
    # Clean the delay station name
    # Attempt to generalize keywords from delay station names
    cleaned_delay_station = delay_station.upper()
    # Replace ' AND ' with space to treat as separate keywords
    cleaned_delay_station = cleaned_delay_station.replace(' AND ', ' ')
    # Remove common suffixes/words that might not appear in stop_name consistently
    cleaned_delay_station = cleaned_delay_station.replace(' STATION', '').replace(' INTERSECTION', '').replace(' AT ', ' ').replace(' BLVD', '').replace(' DR', '').strip()
    # Split into keywords
    keywords = [kw.strip() for kw in cleaned_delay_station.split() if kw.strip()]

    if not keywords: # Handle cases where cleaning results in an empty string
        station_to_coords[delay_station] = (np.nan, np.nan)
        continue

    # Filter df_route_stops where all keywords are present in the cleaned_stop_name
    # This allows for partial matches and flexible ordering of keywords
    mask = df_route_stops['cleaned_stop_name'].apply(lambda x: all(kw in x for kw in keywords))
    matching_stops = df_route_stops[mask]

    if not matching_stops.empty:
        # Calculate mean lat/lon for all matching stops
        mean_lat = matching_stops['stop_lat'].mean()
        mean_lon = matching_stops['stop_lon'].mean()
        station_to_coords[delay_station] = (mean_lat, mean_lon)
    else:
        # If no match found, store NaN
        station_to_coords[delay_station] = (np.nan, np.nan)

print(f"Created coordinate mapping for {len(station_to_coords)} unique delay stations.")

Created coordinate mapping for 12254 unique delay stations.

In [195]:
# --- Step 2: Add latitude and longitude columns to delay_dataset ---
# Using .copy() to avoid SettingWithCopyWarning
delay_dataset_with_coords = delay_dataset.copy()

delay_dataset_with_coords['latitude'] = delay_dataset_with_coords['Station'].map(lambda x: station_to_coords.get(x, (np.nan, np.nan))[0])
delay_dataset_with_coords['longitude'] = delay_dataset_with_coords['Station'].map(lambda x: station_to_coords.get(x, (np.nan, np.nan))[1])

# Filter out rows where latitude or longitude could not be determined
# These are delay entries for which no matching stop could be found in df_route_stops
delay_dataset_with_coords = delay_dataset_with_coords.dropna(subset=['latitude', 'longitude'])

print(f"Original delay_dataset had {delay_dataset.shape[0]} rows.")
print(f"After mapping coordinates, {delay_dataset_with_coords.shape[0]} rows have valid coordinates.")

# --- Step 3: Create a GeoDataFrame from delay_dataset_with_coords ---
gdf_delay_points = gpd.GeoDataFrame(
    delay_dataset_with_coords,
    geometry=gpd.points_from_xy(delay_dataset_with_coords.longitude, delay_dataset_with_coords.latitude),
    crs="EPSG:4326" # Ensure CRS matches the neighborhoods GeoDataFrame
)

print(f"Created GeoDataFrame with {gdf_delay_points.shape[0]} delay points.")

Original delay_dataset had 69037 rows.
After mapping coordinates, 57607 rows have valid coordinates.
Created GeoDataFrame with 57607 delay points.

At this point, I'll just disregard the 12000 rows that I can't map.  I'll work on that later.

In [196]:
gdf_neighborhoods_full.head()

,_id,AREA_ID,AREA_ATTR_ID,PARENT_AREA_ID,AREA_SHORT_CODE,AREA_LONG_CODE,AREA_NAME,AREA_DESC,CLASSIFICATION,CLASSIFICATION_CODE,OBJECTID,geometry,Neighbourhood Number,TSNS 2020 Designation,Total - Age groups of the population - 25% sample data,Median after-tax income of household in 2020 ($),Average after-tax income of household in 2020 ($),Total - Private households by tenure - 25% sample data,Owner,Renter,Total - Citizenship for the population in private households - 25% sample data,Canadian citizens,Not Canadian citizens,Total - Immigrant status and period of immigration for the population in private households - 25% sample data,Non-immigrants,Immigrants,Total - Place of work status for the employed labour force aged 15 years and over - 25% sample data,Worked at home,Worked outside Canada,No fixed workplace address,Usual place of work,Total - Commuting destination for the employed labour force aged 15 years and over with a usual place of work - 25% sample data,Commute within census subdivision (CSD) of residence,Commute to a different census subdivision (CSD) within census division (CD) of residence,Commute to a different census subdivision (CSD) and census division (CD) within province or territory of residence,Commute to a different province or territory,Total - Main mode of commuting for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data,"Car, truck or van","Car, truck or van - as a driver","Car, truck or van - as a passenger",Public transit,Walked,Bicycle,Other method,Total - Commuting duration for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data,Less than 15 minutes,15 to 29 minutes,30 to 44 minutes,45 to 59 minutes,60 minutes and over,Total - Time leaving for work for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data,Between 5 a.m. and 5:59 a.m.,Between 6 a.m. and 6:59 a.m.,Between 7 a.m. and 7:59 a.m.,Between 8 a.m. and 8:59 a.m.,Between 9 a.m. and 11:59 a.m.,Between 12 p.m. and 4:59 a.m.
0,1,2502366,26022881,None,174,174,South Eglinton-Davisville,South Eglinton-Davisville (174),Not an NIA or Emerging Neighbourhood,NA,17824737.0,"MULTIPOLYGON (((-79.38635 43.69783, -79.38623 ...",174,Not an NIA or Emerging Neighbourhood,22735,68500,82100,13185,4010,9170,22735,16525,6210,22735,11005,9360,13475,7330,95,855,5195,5200,4560,0,610,30,6055,2410,2155,255,2655,665,110,215,6055,930,1905,2005,665,550,6055,175,600,1360,1800,1390,730
1,2,2502365,26022880,None,173,173,North Toronto,North Toronto (173),Not an NIA or Emerging Neighbourhood,NA,17824753.0,"MULTIPOLYGON (((-79.39744 43.70693, -79.39837 ...",173,Not an NIA or Emerging Neighbourhood,15885,61200,70900,9430,1750,7680,15885,10945,4945,15885,6625,7135,9460,4890,35,660,3880,3880,3315,0,555,10,4540,1760,1565,195,1950,545,150,145,4540,640,1220,1670,550,465,4540,140,570,1060,1255,970,550
2,3,2502364,26022879,None,172,172,Dovercourt Village,Dovercourt Village (172),Not an NIA or Emerging Neighbourhood,NA,17824769.0,"MULTIPOLYGON (((-79.43411 43.66015, -79.43537 ...",172,Not an NIA or Emerging Neighbourhood,12380,77000,92300,5310,2900,2410,12380,11045,1340,12380,7450,4445,6430,2910,20,720,2775,2775,2495,0,270,0,3495,1645,1425,215,965,390,395,105,3495,600,1115,1115,385,285,3495,185,460,690,825,775,570
3,4,2502363,26022878,None,171,171,Junction-Wallace Emerson,Junction-Wallace Emerson (171),Not an NIA or Emerging Neighbourhood,NA,17824785.0,"MULTIPOLYGON (((-79.4387 43.66766, -79.43841 4...",171,Not an NIA or Emerging Neighbourhood,23180,75000,86700,10185,5105,5080,23180,19960,3225,23180,13320,9020,12070,5135,20,1660,5260,5260,4620,0,635,0,6925,3430,2945,485,2275,610,350,270,6925,1015,2135,2225,845,715,6925,475,1195,1335,1635,1185,1105
4,5,2502362,26022877,None,170,170,Yonge-Bay Corridor,Yonge-Bay Corridor (170),Not an NIA or Emerging Neighbourhood,NA,17824801.0,"MULTIPOLYGON (((-79.38404 43.64497, -79.38502 ...",170,Not an NIA or Emerging Neighbourhood,12645,60400,77700,7465,2405,5055,12645,8155,4490,12645,4590,5630,7475,4145,80,335,2905,2905,2640,0,260,0,3240,640,550,85,685,1675,125,125,3240,1155,1055,610,200,230,3240,60,355,745,1050,695,330

In [197]:
# --- Step 4: Perform the Spatial Join with neighborhoods ---
# Perform a left spatial join to keep all delay entries that have coordinates,
# and append neighborhood information if a point falls within a neighborhood.
# If a point doesn't fall within any neighborhood, 'AREA_NAME' and 'AREA_SHORT_CODE' will be NaN.
delay_with_neighborhood = gpd.sjoin(gdf_delay_points, gdf_neighborhoods_full, how="left", predicate="within")

# Drop the 'index_right' column which is a byproduct of the sjoin operation and usually not needed
delay_with_neighborhood = delay_with_neighborhood.drop(columns=['index_right'])

# --- Step 5: Review results ---
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 20)

display(delay_with_neighborhood.head())

print(f"\nFinal shape of delay data joined with neighborhood information: {delay_with_neighborhood.shape}")
print(f"Number of delay entries successfully mapped to a specific neighborhood: {delay_with_neighborhood['AREA_NAME'].notna().sum()}")
print(f"Number of delay entries with coordinates but not falling into a defined neighborhood: {delay_with_neighborhood['AREA_NAME'].isna().sum()}")

,_id_left,Date,Line,Time,Day,Station,Code,Min Delay,Min Gap,Bound,Vehicle,latitude,longitude,geometry,_id_right,AREA_ID,AREA_ATTR_ID,PARENT_AREA_ID,AREA_SHORT_CODE,AREA_LONG_CODE,AREA_NAME,AREA_DESC,CLASSIFICATION,CLASSIFICATION_CODE,OBJECTID,Neighbourhood Number,TSNS 2020 Designation,Total - Age groups of the population - 25% sample data,Median after-tax income of household in 2020 ($),Average after-tax income of household in 2020 ($),Total - Private households by tenure - 25% sample data,Owner,Renter,Total - Citizenship for the population in private households - 25% sample data,Canadian citizens,Not Canadian citizens,Total - Immigrant status and period of immigration for the population in private households - 25% sample data,Non-immigrants,Immigrants,Total - Place of work status for the employed labour force aged 15 years and over - 25% sample data,Worked at home,Worked outside Canada,No fixed workplace address,Usual place of work,Total - Commuting destination for the employed labour force aged 15 years and over with a usual place of work - 25% sample data,Commute within census subdivision (CSD) of residence,Commute to a different census subdivision (CSD) within census division (CD) of residence,Commute to a different census subdivision (CSD) and census division (CD) within province or territory of residence,Commute to a different province or territory,Total - Main mode of commuting for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data,"Car, truck or van","Car, truck or van - as a driver","Car, truck or van - as a passenger",Public transit,Walked,Bicycle,Other method,Total - Commuting duration for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data,Less than 15 minutes,15 to 29 minutes,30 to 44 minutes,45 to 59 minutes,60 minutes and over,Total - Time leaving for work for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data,Between 5 a.m. and 5:59 a.m.,Between 6 a.m. and 6:59 a.m.,Between 7 a.m. and 7:59 a.m.,Between 8 a.m. and 8:59 a.m.,Between 9 a.m. and 11:59 a.m.,Between 12 p.m. and 4:59 a.m.
0,1,2025-01-01,102 MARKHAM ROAD,02:15,Wednesday,WARDEN STATION,MFESA,20,40,N,3442,43.769610,-79.304280,POINT (-79.30428 43.76961),70.0,2502297.0,26022812.0,None,119.0,119,Wexford/Maryvale,Wexford/Maryvale (119),Not an NIA or Emerging Neighbourhood,NA,17825841.0,119.0,Not an NIA or Emerging Neighbourhood,28345,74000,85800,10260,6050,4220,28340,23620,4720,28340,12365,14400,12445,3120,25,1805,7490,7490,6240,0,1240,10,9300,6300,5485,815,2290,405,35,265,9300,1815,2840,2395,975,1270,9300,650,1285,1905,1845,1665,1950
1,2,2025-01-01,65 PARLIAMENT,02:15,Wednesday,KIPLING STATION,MFUS,0,0,None,0,43.676448,-79.551377,POINT (-79.55138 43.67645),145.0,2502222.0,26022737.0,None,10.0,010,Princess-Rosethorn,Princess-Rosethorn (10),Not an NIA or Emerging Neighbourhood,NA,17827041.0,10.0,Not an NIA or Emerging Neighbourhood,11170,133000,164200,3900,3310,590,11170,10460,710,11170,7615,3400,5215,2260,15,490,2450,2450,1770,0,675,0,2940,2435,2230,205,290,95,15,110,2940,640,1085,705,270,240,2940,105,360,730,865,625,260
2,3,2025-01-01,64 MAIN,02:40,Wednesday,BROADVIEW STATION,MFUI,0,0,None,8546,43.674153,-79.355380,POINT (-79.35538 43.67415),88.0,2502279.0,26022794.0,None,68.0,068,North Riverdale,North Riverdale (68),Not an NIA or Emerging Neighbourhood,NA,17826129.0,68.0,Not an NIA or Emerging Neighbourhood,11290,93000,127900,4905,2855,2045,11290,10680,610,11290,8395,2720,5760,3145,25,395,2205,2205,2010,0,175,20,2600,1155,1020,130,615,465,270,90,2600,460,1010,725,215,190,2600,40,280,690,770,600,225
3,4,2025-01-01,100 FLEMINGDON PARK,02:43,Wednesday,OVERLEA AND THORNCLIFF,MFSAN,17,32,N,8693,43.706435,-79.345772,POINT (-79.34577 43.70644),130.0,2502237.0,26022752.0,None,55.0,055,Thorncliffe Park,Thorncliffe Park (55),Neighbourhood Improvement Area,NIA,17826801.0,55.0,Neighbourhood Improvement Area,20400,62400,68500,7065,990,6070,20400,15215,5185,20400,6420,12905,7140,2130,50,1330,3630,3630,3070,0,550,10,4960,2880,2590,285,1465,405,40,165,4960,925,1285,1380,715,655,4960,245,640,985,920,940,1230
4,5,2025-01-01,34 EGLINTON EAST,03:05,Wednesday,EGLINTON AND DON MILLS,MFUI,20,40,W,8801,43.720512,-79.338919,POINT (-79.33892 43.72051),111.0,2502256.0,26022771.0,None,42.0,042,Banbury-Don Mills,Banbury-Don Mills (42),Not an NIA or Emerging Neighbourhood,NA,17826497.0,42.0,Not an NIA or Emerging Neighbourhood,27155,78000,109700,12215,7295,4915,27150,23375,3780,27150,12640,13675,12325,5305,190,980,5850,5855,4940,0,895,15,6835,5015,4540,480,1145,335,65,270,6835,1130,2610,1865,600,635,6835,260,800,1490,2020,1540,720

Final shape of delay data joined with neighborhood information: (57607, 70)
Number of delay entries successfully mapped to a specific neighborhood: 56206
Number of delay entries with coordinates but not falling into a defined neighborhood: 1401

In [198]:
delay_with_neighborhood.describe()

,_id_left,Date,Min Delay,Min Gap,Vehicle,latitude,longitude,_id_right,AREA_ID,AREA_ATTR_ID,AREA_SHORT_CODE,OBJECTID,Neighbourhood Number
count,57607.000000,57607,57607.000000,57607.000000,57607.000000,57607.000000,57607.000000,56206.000000,5.620600e+04,5.620600e+04,56206.000000,5.620600e+04,56206.000000
mean,34433.233791,2025-07-24 18:56:47.210929152,19.785321,32.107851,5991.787456,43.728998,-79.389167,73.271537,2.502294e+06,2.602281e+07,92.266004,1.782589e+07,92.266004
min,1.000000,2025-01-01 00:00:00,0.000000,0.000000,0.000000,43.591961,-79.649837,1.000000,2.502209e+06,2.602272e+07,1.000000,1.782474e+07,1.000000
25%,17321.500000,2025-04-20 00:00:00,8.000000,16.000000,3334.000000,43.688775,-79.475772,30.000000,2.502248e+06,2.602276e+07,39.000000,1.782520e+07,39.000000
50%,34441.000000,2025-07-26 00:00:00,12.000000,22.000000,7121.000000,43.731833,-79.392350,70.000000,2.502297e+06,2.602281e+07,107.000000,1.782584e+07,107.000000
75%,51564.500000,2025-10-31 00:00:00,20.000000,40.000000,8615.500000,43.769269,-79.297344,119.000000,2.502337e+06,2.602285e+07,142.000000,1.782662e+07,142.000000
max,69036.000000,2026-01-31 00:00:00,999.000000,997.000000,94633.000000,43.909707,-79.123111,158.000000,2.502366e+06,2.602288e+07,174.000000,1.782725e+07,174.000000
std,19867.615104,NaN,46.706590,48.791100,3703.852752,0.051271,0.109436,48.896324,4.889632e+01,4.889632e+01,53.214699,7.823412e+02,53.214699

# Data Cleanup

There are a lot of unnecessary columns, so I'll drop them here.

Also, some columns need to be normalized, and we should do that here as well

In [199]:
cols_to_drop = ['_id_left', 'geometry', '_id_right','AREA_ID',
                'AREA_ATTR_ID','PARENT_AREA_ID', 'AREA_LONG_CODE',
                'OBJECTID', 'Neighbourhood Number',
                'TSNS 2020 Designation']

delay_with_neighborhood.drop(columns=cols_to_drop, inplace=True)

In [200]:
delay_with_neighborhood.shape

(57607, 60)

In [201]:
print(delay_with_neighborhood.dtypes)

Date                                                                                                                                                              datetime64[ns]
Line                                                                                                                                                                      object
Time                                                                                                                                                                      object
Day                                                                                                                                                                       object
Station                                                                                                                                                                   object
Code                                                                                                                                                                      object
Min Delay                                                                                                                                                                  int64
Min Gap                                                                                                                                                                    int64
Bound                                                                                                                                                                     object
Vehicle                                                                                                                                                                    int64
latitude                                                                                                                                                                 float64
longitude                                                                                                                                                                float64
AREA_SHORT_CODE                                                                                                                                                          float64
AREA_NAME                                                                                                                                                                 object
AREA_DESC                                                                                                                                                                 object
CLASSIFICATION                                                                                                                                                            object
CLASSIFICATION_CODE                                                                                                                                                       object
Total - Age groups of the population - 25% sample data                                                                                                                    object
  Median after-tax income of household in 2020 ($)                                                                                                                        object
  Average after-tax income of household in 2020 ($)                                                                                                                       object
Total - Private households by tenure - 25% sample data                                                                                                                    object
  Owner                                                                                                                                                                   object
  Renter                                                                                                                                                                  object
Total - Citizenship for the population in private households - 25% sample data                                                                                            object
  Canadian citizens                                                                                                                                                       object
  Not Canadian citizens                                                                                                                                                   object
Total - Immigrant status and period of immigration for the population in private households - 25% sample data                                                             object
  Non-immigrants                                                                                                                                                          object
  Immigrants                                                                                                                                                              object
Total - Place of work status for the employed labour force aged 15 years and over - 25% sample data                                                                       object
  Worked at home                                                                                                                                                          object
  Worked outside Canada                                                                                                                                                   object
  No fixed workplace address                                                                                                                                              object
  Usual place of work                                                                                                                                                     object
Total - Commuting destination for the employed labour force aged 15 years and over with a usual place of work - 25% sample data                                           object
  Commute within census subdivision (CSD) of residence                                                                                                                    object
  Commute to a different census subdivision (CSD) within census division (CD) of residence                                                                                object
  Commute to a different census subdivision (CSD) and census division (CD) within province or territory of residence                                                      object
  Commute to a different province or territory                                                                                                                            object
Total - Main mode of commuting for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data            object
  Car, truck or van                                                                                                                                                       object
    Car, truck or van - as a driver                                                                                                                                       object
    Car, truck or van - as a passenger                                                                                                                                    object
  Public transit                                                                                                                                                          object
  Walked                                                                                                                                                                  object
  Bicycle                                                                                                                                                                 object
  Other method                                                                                                                                                            object
Total - Commuting duration for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data                object
  Less than 15 minutes                                                                                                                                                    object
  15 to 29 minutes                                                                                                                                                        object
  30 to 44 minutes                                                                                                                                                        object
  45 to 59 minutes                                                                                                                                                        object
  60 minutes and over                                                                                                                                                     object
Total - Time leaving for work for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data             object
  Between 5 a.m. and 5:59 a.m.                                                                                                                                            object
  Between 6 a.m. and 6:59 a.m.                                                                                                                                            object
  Between 7 a.m. and 7:59 a.m.                                                                                                                                            object
  Between 8 a.m. and 8:59 a.m.                                                                                                                                            object
  Between 9 a.m. and 11:59 a.m.                                                                                                                                           object
  Between 12 p.m. and 4:59 a.m.                                                                                                                                           object
dtype: object

In [202]:
# convert the AREA_SHORT_CODE to int64
print(delay_with_neighborhood['AREA_SHORT_CODE'].isna().sum() )

# currently just drop the rows that we can't map to a neighborhood
delay_with_neighborhood.dropna(subset=['AREA_SHORT_CODE'], inplace=True)

1401

In [203]:
delay_with_neighborhood.shape

(56206, 60)

In [204]:
# convert AREA_SHORT_CODE from float to int
delay_with_neighborhood['AREA_SHORT_CODE'].astype('int64')

0        119
1         10
2         68
3         55
4         42
        ...
69030    111
69031      4
69032    112
69033    126
69035    144
Name: AREA_SHORT_CODE, Length: 56206, dtype: int64

# Writing Data out to Excel File

In [205]:
# write out delay_with_neighborhood to a excel file so others can use it
delay_with_neighborhood.to_excel(pathToGroup + "/delay_with_neighborhood.xlsx")

# writing out a json file gave me problems
#delay_with_neighborhood.to_file(pathToGroup + "/delay_neighborhoods.json", driver="GeoJSON")

In [206]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 30)

delay_with_neighborhood.head(10)

,Date,Line,Time,Day,Station,Code,Min Delay,Min Gap,Bound,Vehicle,latitude,longitude,AREA_SHORT_CODE,AREA_NAME,AREA_DESC,CLASSIFICATION,CLASSIFICATION_CODE,Total - Age groups of the population - 25% sample data,Median after-tax income of household in 2020 ($),Average after-tax income of household in 2020 ($),Total - Private households by tenure - 25% sample data,Owner,Renter,Total - Citizenship for the population in private households - 25% sample data,Canadian citizens,Not Canadian citizens,Total - Immigrant status and period of immigration for the population in private households - 25% sample data,Non-immigrants,Immigrants,Total - Place of work status for the employed labour force aged 15 years and over - 25% sample data,Worked at home,Worked outside Canada,No fixed workplace address,Usual place of work,Total - Commuting destination for the employed labour force aged 15 years and over with a usual place of work - 25% sample data,Commute within census subdivision (CSD) of residence,Commute to a different census subdivision (CSD) within census division (CD) of residence,Commute to a different census subdivision (CSD) and census division (CD) within province or territory of residence,Commute to a different province or territory,Total - Main mode of commuting for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data,"Car, truck or van","Car, truck or van - as a driver","Car, truck or van - as a passenger",Public transit,Walked,Bicycle,Other method,Total - Commuting duration for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data,Less than 15 minutes,15 to 29 minutes,30 to 44 minutes,45 to 59 minutes,60 minutes and over,Total - Time leaving for work for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data,Between 5 a.m. and 5:59 a.m.,Between 6 a.m. and 6:59 a.m.,Between 7 a.m. and 7:59 a.m.,Between 8 a.m. and 8:59 a.m.,Between 9 a.m. and 11:59 a.m.,Between 12 p.m. and 4:59 a.m.
0,2025-01-01,102 MARKHAM ROAD,02:15,Wednesday,WARDEN STATION,MFESA,20,40,N,3442,43.769610,-79.304280,119.0,Wexford/Maryvale,Wexford/Maryvale (119),Not an NIA or Emerging Neighbourhood,NA,28345,74000,85800,10260,6050,4220,28340,23620,4720,28340,12365,14400,12445,3120,25,1805,7490,7490,6240,0,1240,10,9300,6300,5485,815,2290,405,35,265,9300,1815,2840,2395,975,1270,9300,650,1285,1905,1845,1665,1950
1,2025-01-01,65 PARLIAMENT,02:15,Wednesday,KIPLING STATION,MFUS,0,0,None,0,43.676448,-79.551377,10.0,Princess-Rosethorn,Princess-Rosethorn (10),Not an NIA or Emerging Neighbourhood,NA,11170,133000,164200,3900,3310,590,11170,10460,710,11170,7615,3400,5215,2260,15,490,2450,2450,1770,0,675,0,2940,2435,2230,205,290,95,15,110,2940,640,1085,705,270,240,2940,105,360,730,865,625,260
2,2025-01-01,64 MAIN,02:40,Wednesday,BROADVIEW STATION,MFUI,0,0,None,8546,43.674153,-79.355380,68.0,North Riverdale,North Riverdale (68),Not an NIA or Emerging Neighbourhood,NA,11290,93000,127900,4905,2855,2045,11290,10680,610,11290,8395,2720,5760,3145,25,395,2205,2205,2010,0,175,20,2600,1155,1020,130,615,465,270,90,2600,460,1010,725,215,190,2600,40,280,690,770,600,225
3,2025-01-01,100 FLEMINGDON PARK,02:43,Wednesday,OVERLEA AND THORNCLIFF,MFSAN,17,32,N,8693,43.706435,-79.345772,55.0,Thorncliffe Park,Thorncliffe Park (55),Neighbourhood Improvement Area,NIA,20400,62400,68500,7065,990,6070,20400,15215,5185,20400,6420,12905,7140,2130,50,1330,3630,3630,3070,0,550,10,4960,2880,2590,285,1465,405,40,165,4960,925,1285,1380,715,655,4960,245,640,985,920,940,1230
4,2025-01-01,34 EGLINTON EAST,03:05,Wednesday,EGLINTON AND DON MILLS,MFUI,20,40,W,8801,43.720512,-79.338919,42.0,Banbury-Don Mills,Banbury-Don Mills (42),Not an NIA or Emerging Neighbourhood,NA,27155,78000,109700,12215,7295,4915,27150,23375,3780,27150,12640,13675,12325,5305,190,980,5850,5855,4940,0,895,15,6835,5015,4540,480,1145,335,65,270,6835,1130,2610,1865,600,635,6835,260,800,1490,2020,1540,720
5,2025-01-01,320 YONGE,03:15,Wednesday,YONGE AND ELM,MFUS,0,0,None,0,43.715842,-79.398512,99.0,Mount Pleasant East,Mount Pleasant East (99),Not an NIA or Emerging Neighbourhood,NA,16370,92000,132800,7170,3950,3220,16370,14745,1625,16370,11305,4620,8345,4755,20,430,3140,3140,2825,0,310,0,3570,2055,1895,160,805,460,80,170,3570,690,1305,1010,345,220,3570,90,350,975,1075,745,330
6,2025-01-01,307 BATHURST,03:20,Wednesday,BATHURST AND DUNDAS,MFUS,0,0,N,0,43.652310,-79.406048,81.0,Trinity-Bellwoods,Trinity-Bellwoods (81),Not an NIA or Emerging Neighbourhood,NA,15415,79500,103800,6840,3800,3040,15415,13465,1945,15415,9250,5545,8290,4280,0,810,3200,3200,2855,0,335,10,4005,1645,1380,265,925,810,425,195,4005,835,1220,1195,310,440,4005,185,430,740,1070,1090,485
7,2025-01-01,320 YONGE,03:23,Wednesday,YONGE AND SHUTER,MFSAN,5,10,N,3468,43.654060,-79.379971,168.0,Downtown Yonge East,Downtown Yonge East (168),Not an NIA or Emerging Neighbourhood,NA,17700,61600,76500,11050,3990,7065,17695,13120,4580,17695,8200,7120,10495,6140,45,490,3825,3825,3380,0,420,25,4310,1145,980,165,1150,1655,195,160,4310,1065,1565,950,390,345,4310,70,420,935,1360,945,585
8,2025-01-01,112 WEST MALL,03:39,Wednesday,RENFORTH STATION,SFO,0,0,None,3306,43.662013,-79.585597,11.0,Eringate-Centennial-West Deane,Eringate-Centennial-West Deane (11),Not an NIA or Emerging Neighbourhood,NA,18450,93000,105600,6845,5740,1105,18450,17220,1230,18450,10295,7870,8510,2930,35,955,4590,4595,3020,0,1570,0,5545,4400,3950,445,755,150,40,205,5545,1100,2050,1350,440,610,5545,300,825,1415,1260,895,865
9,2025-01-01,39 FINCH EAST,04:38,Wednesday,FINCH AND MCCOWAN,EFO,16,32,W,3144,43.808115,-79.266663,129.0,Agincourt North,Agincourt North (129),Not an NIA or Emerging Neighbourhood,NA,27540,76500,85700,9090,7135,1950,27540,22145,5395,27540,7700,18665,10860,2885,80,1320,6570,6570,4670,0,1895,10,7895,6045,5120,920,1465,190,55,140,7895,1315,2515,2095,795,1170,7895,350,865,1550,1605,2100,1425